### ISSUE TITLE
6 communes ont une géometrie vide

### ISSUE THREAD

**Issue by jengelaere** [MaelTheuliere/COGiter#10]
`filter(communes_geo, st_is_empty(communes_geo$geometry))` retourne 6 communes :
```
  DEPCOM                 geometry
  <fct>  <GEOMETRYCOLLECTION [m]>
1 02143  GEOMETRYCOLLECTION EMPTY
2 29083  GEOMETRYCOLLECTION EMPTY
3 59332  GEOMETRYCOLLECTION EMPTY
4 69166  GEOMETRYCOLLECTION EMPTY
5 72043  GEOMETRYCOLLECTION EMPTY
6 85134  GEOMETRYCOLLECTION EMPTY
```
J'ai vérifié dans la fourniture de l'IGN (commune.shp de la métropole), les géométries de ces communes sont initialement valides. La simplification mapshaper a été violente !!

**Comment by MaelTheuliere** [comment]
Merci @jengelaere ! C'est corrigé.
