### ISSUE TITLE
passer_au_cog_a_jour() ne préserve pas les groupes préexistants

### ISSUE THREAD

**Issue by jengelaere** [MaelTheuliere/COGiter#14]
``` r
library(dplyr)
library(COGiter)

data.frame(annee=rep(2010:2015, 10), DEPCOM=paste0("4400",1:5), 
           pop=5001:5060, stringsAsFactors = FALSE) %>%
   group_by(annee) %>%
   passer_au_cog_a_jour(aggrege = TRUE, garder_info_supra = FALSE)

#> # A tibble: 5 x 3
#>   DEPCOM annee   pop
#>   <fct>  <int> <int>
#> 1 44001  24150 60342
#> 2 44002  24150 60354
#> 3 44003  24150 60366
#> 4 44005  24150 60390
#> 5 44163  24150 60378
```
Le problème n'est pas reproduit si les années sont au format factor ou character

**Comment by MaelTheuliere** [comment]
L'idée serait que on rajoute les colonnes de groupement en plus lors de l'aggrégation ?
Et la table en sortie garde les variables de groupe de celle en entrée ?
Sachant que normalement c'est une mauvaise pratique d'avoir l'année en numérique, mais ce seriat logique en effet dans l'esprit tidyverse.
