### ISSUE TITLE
Tester les EPCI sur deux régions

### ISSUE THREAD

**Issue by statnmap** [MaelTheuliere/COGiter#31]
Il est possible qu'il y ait des problèmes de tests sur des EPCI comme `epci <- "200055655"` à cheval sur deux départements.

**Comment by MaelTheuliere** [comment]
J'ai pris en compte le problème pour les rattachements supra.
Pour l'instant ça donne ça :

```
COGiter::code_epci_existe("200055655")
#> [1] TRUE
COGiter::code_dep_of_epci("200055655")
#> [[1]]
#> [1] "77" "95"
COGiter::code_reg_of_epci("200055655")
#> [[1]]
#> [1] "11"

```

**Comment by jengelaere** [comment]
@statnmap Ce comportement te convient-il ? On peut fermer le ticket ?

**Comment by statnmap** [comment]
Je pense que nous n'avons pas eu de nouveaux problèmes, donc on peut considérer que c'est réglé. Merci.
