### ISSUE TITLE
Pb mise à jour des tables liste_zone, zonage_abc_r52, zonage_pinel_r52

### ISSUE THREAD

**Issue by jengelaere** [MaelTheuliere/COGiter#6]
Il semble que la table **liste_zone** ne soit pas à jour.
Par ex, on n'y trouve pas le code EPCI _200083392_ qui correspond à la CA de Laval dans les autres tables. Dans liste_zone, la commune de Laval (53130) appartient à l'EPCI _245300330_, ce qui semble être l'ancien code epci de l'agglo.
En faisant tourner le script de création de la table localement, j'obtiens une table de 36349 obs, qui contient le bon siret pour l'agglo de laval.
Il manque peut-être simplement `use_data(liste_zone,internal=F,overwrite = T)` en fin de raw_data_2019.R
Les tables de zonages abc et pinel ne semble pas avoir bougé non plus.

**Comment by MaelTheuliere** [comment]
pris en charge avec la version 0.0.1.9000 cf28ae171e9479426db0332105140ff1fe492c06

**Comment by MaelTheuliere** [comment]
Helle Juliette, les tables zonage_abc_r52 et zonage_pinel_r52 ne sont pas encore à jour en effet car je n'ai pas eu de codification officielle de ces données. J'avais toutefois regardé que les fusions intervenu en 2019 ne semblaient pas générer de conflit de fusion (toutes les communes fusionnées avaient au départ le même zonage)
